os: linux
dist: xenial
language: generic
env: 
  - export CODACY_PROJECT_TOKEN=9a6ad026f80f4b8e8047fb617ec63e2a
before_build:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info