language: generic
services:
  - docker
env: 
  - export CODACY_PROJECT_TOKEN=9a6ad026f80f4b8e8047fb617ec63e2a
before_install:
  - docker build -t projectx:latest .
after_success:
<<<<<<< HEAD
bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
=======
  bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
>>>>>>> a304ec9da2bd27245bb27d1ab37b5a52b2ec8b57
  
