os: linux
dist: xenial
env:
  global:
    - CODACY_PROJECT_TOKEN=9a6ad026f80f4b8e8047fb617ec63e2a
    - CC_TEST_REPORTER_ID=f3a706d01a86b6d81baa28142b579a0e6dd798cc8e12059d982921e9aa9f73cb
    - language: generic
      after_sucess:
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
        - ./cc-test-reporter report -r lcov coverage/lcov.info
        - ./cc-test-reporter upload-coverage || true
      scripts:
        - yarn jest test --coverage