os: linux
dist: xenial
env:
  global:
    - export CODACY_PROJECT_TOKEN=9a6ad026f80f4b8e8047fb617ec63e2a
jobs:
  include:
    - language: generic
      go:
        - master
      after_sucess:
      - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
      - go build utils/server.go

#    - language: dart
#        dart:
#        - stable